<?php
/**
 * @file
 * attac_kalender.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function attac_kalender_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_termine:termine
  $menu_links['main-menu_termine:termine'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'termine',
    'router_path' => 'termine',
    'link_title' => 'Termine',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_termine:termine',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Termine');


  return $menu_links;
}
